"""Training Metrics

Revision ID: 073a3ac70659
Revises: d4620eed9244
Create Date: 2024-04-12 01:04:35.532339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073a3ac70659'
down_revision = 'd4620eed9244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vo2max', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.drop_column('vo2max')
        batch_op.drop_column('ftp')

    # ### end Alembic commands ###
