"""Recreate initial migrations

Revision ID: 0a7369aea052
Revises: 
Create Date: 2024-04-11 22:41:27.733144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7369aea052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('calories_burned', sa.String(), nullable=True),
    sa.Column('training_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_session')
    # ### end Alembic commands ###
