"""Training Metrics

Revision ID: 2b70f348b9ad
Revises: 
Create Date: 2024-04-12 01:04:49.429208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b70f348b9ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vo2max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('power_output', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_heart_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resting_heart_rate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_session', schema=None) as batch_op:
        batch_op.drop_column('resting_heart_rate')
        batch_op.drop_column('max_heart_rate')
        batch_op.drop_column('power_output')
        batch_op.drop_column('vo2max')
        batch_op.drop_column('ftp')

    # ### end Alembic commands ###
